(cl:in-package follow-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          X0-VAL
          X0
          Y0-VAL
          Y0
          X1-VAL
          X1
          Y1-VAL
          Y1
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ANGLEX-VAL
          ANGLEX
          ANGLEY-VAL
          ANGLEY
          DISTANCE-VAL
          DISTANCE
          CONF-VAL
          CONF
          TRACK_ID-VAL
          TRACK_ID
          LABEL-VAL
          LABEL
))