# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from follow/ObstaclePoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ObstaclePoint(genpy.Message):
  _md5sum = "035901bda74cc190cb732ad4fef0a1b0"
  _type = "follow/ObstaclePoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 timestamp
int32 x0
int32 y0
int32 x1
int32 y1
float64 x
float64 y
float64 z
float64 angleX
float64 angleY
float64 distance
float64 conf
int32 track_id
string label"""
  __slots__ = ['timestamp','x0','y0','x1','y1','x','y','z','angleX','angleY','distance','conf','track_id','label']
  _slot_types = ['float64','int32','int32','int32','int32','float64','float64','float64','float64','float64','float64','float64','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,x0,y0,x1,y1,x,y,z,angleX,angleY,distance,conf,track_id,label

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObstaclePoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0.
      if self.x0 is None:
        self.x0 = 0
      if self.y0 is None:
        self.y0 = 0
      if self.x1 is None:
        self.x1 = 0
      if self.y1 is None:
        self.y1 = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.angleX is None:
        self.angleX = 0.
      if self.angleY is None:
        self.angleY = 0.
      if self.distance is None:
        self.distance = 0.
      if self.conf is None:
        self.conf = 0.
      if self.track_id is None:
        self.track_id = 0
      if self.label is None:
        self.label = ''
    else:
      self.timestamp = 0.
      self.x0 = 0
      self.y0 = 0
      self.x1 = 0
      self.y1 = 0
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.angleX = 0.
      self.angleY = 0.
      self.distance = 0.
      self.conf = 0.
      self.track_id = 0
      self.label = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d4i7di().pack(_x.timestamp, _x.x0, _x.y0, _x.x1, _x.y1, _x.x, _x.y, _x.z, _x.angleX, _x.angleY, _x.distance, _x.conf, _x.track_id))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 84
      (_x.timestamp, _x.x0, _x.y0, _x.x1, _x.y1, _x.x, _x.y, _x.z, _x.angleX, _x.angleY, _x.distance, _x.conf, _x.track_id,) = _get_struct_d4i7di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d4i7di().pack(_x.timestamp, _x.x0, _x.y0, _x.x1, _x.y1, _x.x, _x.y, _x.z, _x.angleX, _x.angleY, _x.distance, _x.conf, _x.track_id))
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 84
      (_x.timestamp, _x.x0, _x.y0, _x.x1, _x.y1, _x.x, _x.y, _x.z, _x.angleX, _x.angleY, _x.distance, _x.conf, _x.track_id,) = _get_struct_d4i7di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d4i7di = None
def _get_struct_d4i7di():
    global _struct_d4i7di
    if _struct_d4i7di is None:
        _struct_d4i7di = struct.Struct("<d4i7di")
    return _struct_d4i7di
